# docker-compose up -d

version: '3.5'

services:

  sonatype-nexus3:
    container_name: nexus
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
